---
configure_dotfiles: yes
ahoy_version: 2.0.0
user_home_directory: "{{ lookup('env','HOME') }}"

manjaro_remove_pacman_packages:
  - xfburn
  - gnumeric
  - chromium
  - sylpheed
  - smplayer

pacman_packages:
  - gcc
  - zsh
  - zsh-autosuggestions
  - yaourt
  - terminator
  - tilix
  - vim
  - docker
  - docker-compose
  - bat
  - tree
  - nodejs-lts-carbon
  - npm
  - unzip
  - sshpass
  # virtualbox for vagrant 
  - virtualbox
  - linux414-virtualbox-host-modules
  - linux414-virtualbox-guest-modules
  - vagrant
  - terraform
  - packer
  - python-pip
  - php
  - composer
  - mariadb
  # personalization and themes 
  - arc-gtk-theme
  - moka-icon-theme
  - arc-icon-theme
  - ttf-material-icons
  # polybar and dependencies
  - polybar
  - python-dbus
  - playerctl
  - jsoncpp
  - libmpdclient
  # App launcher
  - rofi
  # Bluetooth
  - bluez
  - bluez-libs
  - bluez-utils
  - blueman
  #Audio
  - pulseaudio
  - paprefs
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pavucontrol

yaourt_packages:
  # fonts and personalization
  - ttf-mac-fonts
  - system-san-francisco-font-git
  - ttf-hack-powerline-git
  - siji-git
  - ttf-font-awesome-4
  - capitaine-cursors
  #you need install this manually
#  - fontconfig-infinality-ultimate
  - google-chrome
  - spotify
  - wavebox-bin
  - visual-studio-code-bin
  - direnv
  - kubernetes-helm
  - minikube
  - pa-applet
