---
- hosts: localhost
  become: true
  
  roles:
  - { role: base, tags: ['base'] }
  - { role: ahoy, tags: ['ahoy'] }
  - { role: docker, tags: ['docker'] }
  - { role: hashicorp, tags: ['hashicorp'] }
  # - { role: bluetooth, tags: ['bluetooth'] }
  # - { role: sound, tags: ['sound'] }

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"