---
- name: Install vagrant
  pacman:
    name: vagrant
    state: present

- name: Install terraform
  pacman:
    name: terraform
    state: present

- name: Install packer
  pacman:
    name: packer
    state: present

